#  Getting and Cleaning Data
#  Course Project
#  Motion Sensor Data

#  Research description and data source:
#  http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 

#  The data as delivered is divided into training and test subsets.
#  Each subset is imported and assembled separately.
#  Then the two subsets are combined for analysis.

#  Motion measure feature list
#  - punctuation removed

feature_names <- 
  c(
    "tBodyAcc_mean_X",
    "tBodyAcc_mean_Y",
    "tBodyAcc_mean_Z",
    "tBodyAcc_std_X",
    "tBodyAcc_std_Y",
    "tBodyAcc_std_Z",
    "tBodyAcc_mad_X",
    "tBodyAcc_mad_Y",
    "tBodyAcc_mad_Z",
    "tBodyAcc_max_X",
    "tBodyAcc_max_Y",
    "tBodyAcc_max_Z",
    "tBodyAcc_min_X",
    "tBodyAcc_min_Y",
    "tBodyAcc_min_Z",
    "tBodyAcc_sma",
    "tBodyAcc_energy_X",
    "tBodyAcc_energy_Y",
    "tBodyAcc_energy_Z",
    "tBodyAcc_iqr_X",
    "tBodyAcc_iqr_Y",
    "tBodyAcc_iqr_Z",
    "tBodyAcc_entropy_X",
    "tBodyAcc_entropy_Y",
    "tBodyAcc_entropy_Z",
    "tBodyAcc_arCoeff_X1",
    "tBodyAcc_arCoeff_X2",
    "tBodyAcc_arCoeff_X3",
    "tBodyAcc_arCoeff_X4",
    "tBodyAcc_arCoeff_Y1",
    "tBodyAcc_arCoeff_Y2",
    "tBodyAcc_arCoeff_Y3",
    "tBodyAcc_arCoeff_Y4",
    "tBodyAcc_arCoeff_Z1",
    "tBodyAcc_arCoeff_Z2",
    "tBodyAcc_arCoeff_Z3",
    "tBodyAcc_arCoeff_Z4",
    "tBodyAcc_correlation_XY",
    "tBodyAcc_correlation_XZ",
    "tBodyAcc_correlation_YZ",
    "tGravityAcc_mean_X",
    "tGravityAcc_mean_Y",
    "tGravityAcc_mean_Z",
    "tGravityAcc_std_X",
    "tGravityAcc_std_Y",
    "tGravityAcc_std_Z",
    "tGravityAcc_mad_X",
    "tGravityAcc_mad_Y",
    "tGravityAcc_mad_Z",
    "tGravityAcc_max_X",
    "tGravityAcc_max_Y",
    "tGravityAcc_max_Z",
    "tGravityAcc_min_X",
    "tGravityAcc_min_Y",
    "tGravityAcc_min_Z",
    "tGravityAcc_sma",
    "tGravityAcc_energy_X",
    "tGravityAcc_energy_Y",
    "tGravityAcc_energy_Z",
    "tGravityAcc_iqr_X",
    "tGravityAcc_iqr_Y",
    "tGravityAcc_iqr_Z",
    "tGravityAcc_entropy_X",
    "tGravityAcc_entropy_Y",
    "tGravityAcc_entropy_Z",
    "tGravityAcc_arCoeff_X1",
    "tGravityAcc_arCoeff_X2",
    "tGravityAcc_arCoeff_X3",
    "tGravityAcc_arCoeff_X4",
    "tGravityAcc_arCoeff_Y1",
    "tGravityAcc_arCoeff_Y2",
    "tGravityAcc_arCoeff_Y3",
    "tGravityAcc_arCoeff_Y4",
    "tGravityAcc_arCoeff_Z1",
    "tGravityAcc_arCoeff_Z2",
    "tGravityAcc_arCoeff_Z3",
    "tGravityAcc_arCoeff_Z4",
    "tGravityAcc_correlation_XY",
    "tGravityAcc_correlation_XZ",
    "tGravityAcc_correlation_YZ",
    "tBodyAccJerk_mean_X",
    "tBodyAccJerk_mean_Y",
    "tBodyAccJerk_mean_Z",
    "tBodyAccJerk_std_X",
    "tBodyAccJerk_std_Y",
    "tBodyAccJerk_std_Z",
    "tBodyAccJerk_mad_X",
    "tBodyAccJerk_mad_Y",
    "tBodyAccJerk_mad_Z",
    "tBodyAccJerk_max_X",
    "tBodyAccJerk_max_Y",
    "tBodyAccJerk_max_Z",
    "tBodyAccJerk_min_X",
    "tBodyAccJerk_min_Y",
    "tBodyAccJerk_min_Z",
    "tBodyAccJerk_sma",
    "tBodyAccJerk_energy_X",
    "tBodyAccJerk_energy_Y",
    "tBodyAccJerk_energy_Z",
    "tBodyAccJerk_iqr_X",
    "tBodyAccJerk_iqr_Y",
    "tBodyAccJerk_iqr_Z",
    "tBodyAccJerk_entropy_X",
    "tBodyAccJerk_entropy_Y",
    "tBodyAccJerk_entropy_Z",
    "tBodyAccJerk_arCoeff_X1",
    "tBodyAccJerk_arCoeff_X2",
    "tBodyAccJerk_arCoeff_X3",
    "tBodyAccJerk_arCoeff_X4",
    "tBodyAccJerk_arCoeff_Y1",
    "tBodyAccJerk_arCoeff_Y2",
    "tBodyAccJerk_arCoeff_Y3",
    "tBodyAccJerk_arCoeff_Y4",
    "tBodyAccJerk_arCoeff_Z1",
    "tBodyAccJerk_arCoeff_Z2",
    "tBodyAccJerk_arCoeff_Z3",
    "tBodyAccJerk_arCoeff_Z4",
    "tBodyAccJerk_correlation_XY",
    "tBodyAccJerk_correlation_XZ",
    "tBodyAccJerk_correlation_YZ",
    "tBodyGyro_mean_X",
    "tBodyGyro_mean_Y",
    "tBodyGyro_mean_Z",
    "tBodyGyro_std_X",
    "tBodyGyro_std_Y",
    "tBodyGyro_std_Z",
    "tBodyGyro_mad_X",
    "tBodyGyro_mad_Y",
    "tBodyGyro_mad_Z",
    "tBodyGyro_max_X",
    "tBodyGyro_max_Y",
    "tBodyGyro_max_Z",
    "tBodyGyro_min_X",
    "tBodyGyro_min_Y",
    "tBodyGyro_min_Z",
    "tBodyGyro_sma",
    "tBodyGyro_energy_X",
    "tBodyGyro_energy_Y",
    "tBodyGyro_energy_Z",
    "tBodyGyro_iqr_X",
    "tBodyGyro_iqr_Y",
    "tBodyGyro_iqr_Z",
    "tBodyGyro_entropy_X",
    "tBodyGyro_entropy_Y",
    "tBodyGyro_entropy_Z",
    "tBodyGyro_arCoeff_X1",
    "tBodyGyro_arCoeff_X2",
    "tBodyGyro_arCoeff_X3",
    "tBodyGyro_arCoeff_X4",
    "tBodyGyro_arCoeff_Y1",
    "tBodyGyro_arCoeff_Y2",
    "tBodyGyro_arCoeff_Y3",
    "tBodyGyro_arCoeff_Y4",
    "tBodyGyro_arCoeff_Z1",
    "tBodyGyro_arCoeff_Z2",
    "tBodyGyro_arCoeff_Z3",
    "tBodyGyro_arCoeff_Z4",
    "tBodyGyro_correlation_XY",
    "tBodyGyro_correlation_XZ",
    "tBodyGyro_correlation_YZ",
    "tBodyGyroJerk_mean_X",
    "tBodyGyroJerk_mean_Y",
    "tBodyGyroJerk_mean_Z",
    "tBodyGyroJerk_std_X",
    "tBodyGyroJerk_std_Y",
    "tBodyGyroJerk_std_Z",
    "tBodyGyroJerk_mad_X",
    "tBodyGyroJerk_mad_Y",
    "tBodyGyroJerk_mad_Z",
    "tBodyGyroJerk_max_X",
    "tBodyGyroJerk_max_Y",
    "tBodyGyroJerk_max_Z",
    "tBodyGyroJerk_min_X",
    "tBodyGyroJerk_min_Y",
    "tBodyGyroJerk_min_Z",
    "tBodyGyroJerk_sma",
    "tBodyGyroJerk_energy_X",
    "tBodyGyroJerk_energy_Y",
    "tBodyGyroJerk_energy_Z",
    "tBodyGyroJerk_iqr_X",
    "tBodyGyroJerk_iqr_Y",
    "tBodyGyroJerk_iqr_Z",
    "tBodyGyroJerk_entropy_X",
    "tBodyGyroJerk_entropy_Y",
    "tBodyGyroJerk_entropy_Z",
    "tBodyGyroJerk_arCoeff_X1",
    "tBodyGyroJerk_arCoeff_X2",
    "tBodyGyroJerk_arCoeff_X3",
    "tBodyGyroJerk_arCoeff_X4",
    "tBodyGyroJerk_arCoeff_Y1",
    "tBodyGyroJerk_arCoeff_Y2",
    "tBodyGyroJerk_arCoeff_Y3",
    "tBodyGyroJerk_arCoeff_Y4",
    "tBodyGyroJerk_arCoeff_Z1",
    "tBodyGyroJerk_arCoeff_Z2",
    "tBodyGyroJerk_arCoeff_Z3",
    "tBodyGyroJerk_arCoeff_Z4",
    "tBodyGyroJerk_correlation_XY",
    "tBodyGyroJerk_correlation_XZ",
    "tBodyGyroJerk_correlation_YZ",
    "tBodyAccMag_mean",
    "tBodyAccMag_std",
    "tBodyAccMag_mad",
    "tBodyAccMag_max",
    "tBodyAccMag_min",
    "tBodyAccMag_sma",
    "tBodyAccMag_energy",
    "tBodyAccMag_iqr",
    "tBodyAccMag_entropy",
    "tBodyAccMag_arCoeff1",
    "tBodyAccMag_arCoeff2",
    "tBodyAccMag_arCoeff3",
    "tBodyAccMag_arCoeff4",
    "tGravityAccMag_mean",
    "tGravityAccMag_std",
    "tGravityAccMag_mad",
    "tGravityAccMag_max",
    "tGravityAccMag_min",
    "tGravityAccMag_sma",
    "tGravityAccMag_energy",
    "tGravityAccMag_iqr",
    "tGravityAccMag_entropy",
    "tGravityAccMag_arCoeff1",
    "tGravityAccMag_arCoeff2",
    "tGravityAccMag_arCoeff3",
    "tGravityAccMag_arCoeff4",
    "tBodyAccJerkMag_mean",
    "tBodyAccJerkMag_std",
    "tBodyAccJerkMag_mad",
    "tBodyAccJerkMag_max",
    "tBodyAccJerkMag_min",
    "tBodyAccJerkMag_sma",
    "tBodyAccJerkMag_energy",
    "tBodyAccJerkMag_iqr",
    "tBodyAccJerkMag_entropy",
    "tBodyAccJerkMag_arCoeff1",
    "tBodyAccJerkMag_arCoeff2",
    "tBodyAccJerkMag_arCoeff3",
    "tBodyAccJerkMag_arCoeff4",
    "tBodyGyroMag_mean",
    "tBodyGyroMag_std",
    "tBodyGyroMag_mad",
    "tBodyGyroMag_max",
    "tBodyGyroMag_min",
    "tBodyGyroMag_sma",
    "tBodyGyroMag_energy",
    "tBodyGyroMag_iqr",
    "tBodyGyroMag_entropy",
    "tBodyGyroMag_arCoeff1",
    "tBodyGyroMag_arCoeff2",
    "tBodyGyroMag_arCoeff3",
    "tBodyGyroMag_arCoeff4",
    "tBodyGyroJerkMag_mean",
    "tBodyGyroJerkMag_std",
    "tBodyGyroJerkMag_mad",
    "tBodyGyroJerkMag_max",
    "tBodyGyroJerkMag_min",
    "tBodyGyroJerkMag_sma",
    "tBodyGyroJerkMag_energy",
    "tBodyGyroJerkMag_iqr",
    "tBodyGyroJerkMag_entropy",
    "tBodyGyroJerkMag_arCoeff1",
    "tBodyGyroJerkMag_arCoeff2",
    "tBodyGyroJerkMag_arCoeff3",
    "tBodyGyroJerkMag_arCoeff4",
    "fBodyAcc_mean_X",
    "fBodyAcc_mean_Y",
    "fBodyAcc_mean_Z",
    "fBodyAcc_std_X",
    "fBodyAcc_std_Y",
    "fBodyAcc_std_Z",
    "fBodyAcc_mad_X",
    "fBodyAcc_mad_Y",
    "fBodyAcc_mad_Z",
    "fBodyAcc_max_X",
    "fBodyAcc_max_Y",
    "fBodyAcc_max_Z",
    "fBodyAcc_min_X",
    "fBodyAcc_min_Y",
    "fBodyAcc_min_Z",
    "fBodyAcc_sma",
    "fBodyAcc_energy_X",
    "fBodyAcc_energy_Y",
    "fBodyAcc_energy_Z",
    "fBodyAcc_iqr_X",
    "fBodyAcc_iqr_Y",
    "fBodyAcc_iqr_Z",
    "fBodyAcc_entropy_X",
    "fBodyAcc_entropy_Y",
    "fBodyAcc_entropy_Z",
    "fBodyAcc_maxInds_X",
    "fBodyAcc_maxInds_Y",
    "fBodyAcc_maxInds_Z",
    "fBodyAcc_meanFreq_X",
    "fBodyAcc_meanFreq_Y",
    "fBodyAcc_meanFreq_Z",
    "fBodyAcc_skewness_X",
    "fBodyAcc_kurtosis_X",
    "fBodyAcc_skewness_Y",
    "fBodyAcc_kurtosis_Y",
    "fBodyAcc_skewness_Z",
    "fBodyAcc_kurtosis_Z",
    "fBodyAcc_bandsEnergy_18",
    "fBodyAcc_bandsEnergy_916",
    "fBodyAcc_bandsEnergy_1724",
    "fBodyAcc_bandsEnergy_2532",
    "fBodyAcc_bandsEnergy_3340",
    "fBodyAcc_bandsEnergy_4148",
    "fBodyAcc_bandsEnergy_4956",
    "fBodyAcc_bandsEnergy_5764",
    "fBodyAcc_bandsEnergy_116",
    "fBodyAcc_bandsEnergy_1732",
    "fBodyAcc_bandsEnergy_3348",
    "fBodyAcc_bandsEnergy_4964",
    "fBodyAcc_bandsEnergy_124",
    "fBodyAcc_bandsEnergy_2548",
    "fBodyAcc_bandsEnergy_18",
    "fBodyAcc_bandsEnergy_916",
    "fBodyAcc_bandsEnergy_1724",
    "fBodyAcc_bandsEnergy_2532",
    "fBodyAcc_bandsEnergy_3340",
    "fBodyAcc_bandsEnergy_4148",
    "fBodyAcc_bandsEnergy_4956",
    "fBodyAcc_bandsEnergy_5764",
    "fBodyAcc_bandsEnergy_116",
    "fBodyAcc_bandsEnergy_1732",
    "fBodyAcc_bandsEnergy_3348",
    "fBodyAcc_bandsEnergy_4964",
    "fBodyAcc_bandsEnergy_124",
    "fBodyAcc_bandsEnergy_2548",
    "fBodyAcc_bandsEnergy_18",
    "fBodyAcc_bandsEnergy_916",
    "fBodyAcc_bandsEnergy_1724",
    "fBodyAcc_bandsEnergy_2532",
    "fBodyAcc_bandsEnergy_3340",
    "fBodyAcc_bandsEnergy_4148",
    "fBodyAcc_bandsEnergy_4956",
    "fBodyAcc_bandsEnergy_5764",
    "fBodyAcc_bandsEnergy_116",
    "fBodyAcc_bandsEnergy_1732",
    "fBodyAcc_bandsEnergy_3348",
    "fBodyAcc_bandsEnergy_4964",
    "fBodyAcc_bandsEnergy_124",
    "fBodyAcc_bandsEnergy_2548",
    "fBodyAccJerk_mean_X",
    "fBodyAccJerk_mean_Y",
    "fBodyAccJerk_mean_Z",
    "fBodyAccJerk_std_X",
    "fBodyAccJerk_std_Y",
    "fBodyAccJerk_std_Z",
    "fBodyAccJerk_mad_X",
    "fBodyAccJerk_mad_Y",
    "fBodyAccJerk_mad_Z",
    "fBodyAccJerk_max_X",
    "fBodyAccJerk_max_Y",
    "fBodyAccJerk_max_Z",
    "fBodyAccJerk_min_X",
    "fBodyAccJerk_min_Y",
    "fBodyAccJerk_min_Z",
    "fBodyAccJerk_sma",
    "fBodyAccJerk_energy_X",
    "fBodyAccJerk_energy_Y",
    "fBodyAccJerk_energy_Z",
    "fBodyAccJerk_iqr_X",
    "fBodyAccJerk_iqr_Y",
    "fBodyAccJerk_iqr_Z",
    "fBodyAccJerk_entropy_X",
    "fBodyAccJerk_entropy_Y",
    "fBodyAccJerk_entropy_Z",
    "fBodyAccJerk_maxInds_X",
    "fBodyAccJerk_maxInds_Y",
    "fBodyAccJerk_maxInds_Z",
    "fBodyAccJerk_meanFreq_X",
    "fBodyAccJerk_meanFreq_Y",
    "fBodyAccJerk_meanFreq_Z",
    "fBodyAccJerk_skewness_X",
    "fBodyAccJerk_kurtosis_X",
    "fBodyAccJerk_skewness_Y",
    "fBodyAccJerk_kurtosis_Y",
    "fBodyAccJerk_skewness_Z",
    "fBodyAccJerk_kurtosis_Z",
    "fBodyAccJerk_bandsEnergy_18",
    "fBodyAccJerk_bandsEnergy_916",
    "fBodyAccJerk_bandsEnergy_1724",
    "fBodyAccJerk_bandsEnergy_2532",
    "fBodyAccJerk_bandsEnergy_3340",
    "fBodyAccJerk_bandsEnergy_4148",
    "fBodyAccJerk_bandsEnergy_4956",
    "fBodyAccJerk_bandsEnergy_5764",
    "fBodyAccJerk_bandsEnergy_116",
    "fBodyAccJerk_bandsEnergy_1732",
    "fBodyAccJerk_bandsEnergy_3348",
    "fBodyAccJerk_bandsEnergy_4964",
    "fBodyAccJerk_bandsEnergy_124",
    "fBodyAccJerk_bandsEnergy_2548",
    "fBodyAccJerk_bandsEnergy_18",
    "fBodyAccJerk_bandsEnergy_916",
    "fBodyAccJerk_bandsEnergy_1724",
    "fBodyAccJerk_bandsEnergy_2532",
    "fBodyAccJerk_bandsEnergy_3340",
    "fBodyAccJerk_bandsEnergy_4148",
    "fBodyAccJerk_bandsEnergy_4956",
    "fBodyAccJerk_bandsEnergy_5764",
    "fBodyAccJerk_bandsEnergy_116",
    "fBodyAccJerk_bandsEnergy_1732",
    "fBodyAccJerk_bandsEnergy_3348",
    "fBodyAccJerk_bandsEnergy_4964",
    "fBodyAccJerk_bandsEnergy_124",
    "fBodyAccJerk_bandsEnergy_2548",
    "fBodyAccJerk_bandsEnergy_18",
    "fBodyAccJerk_bandsEnergy_916",
    "fBodyAccJerk_bandsEnergy_1724",
    "fBodyAccJerk_bandsEnergy_2532",
    "fBodyAccJerk_bandsEnergy_3340",
    "fBodyAccJerk_bandsEnergy_4148",
    "fBodyAccJerk_bandsEnergy_4956",
    "fBodyAccJerk_bandsEnergy_5764",
    "fBodyAccJerk_bandsEnergy_116",
    "fBodyAccJerk_bandsEnergy_1732",
    "fBodyAccJerk_bandsEnergy_3348",
    "fBodyAccJerk_bandsEnergy_4964",
    "fBodyAccJerk_bandsEnergy_124",
    "fBodyAccJerk_bandsEnergy_2548",
    "fBodyGyro_mean_X",
    "fBodyGyro_mean_Y",
    "fBodyGyro_mean_Z",
    "fBodyGyro_std_X",
    "fBodyGyro_std_Y",
    "fBodyGyro_std_Z",
    "fBodyGyro_mad_X",
    "fBodyGyro_mad_Y",
    "fBodyGyro_mad_Z",
    "fBodyGyro_max_X",
    "fBodyGyro_max_Y",
    "fBodyGyro_max_Z",
    "fBodyGyro_min_X",
    "fBodyGyro_min_Y",
    "fBodyGyro_min_Z",
    "fBodyGyro_sma",
    "fBodyGyro_energy_X",
    "fBodyGyro_energy_Y",
    "fBodyGyro_energy_Z",
    "fBodyGyro_iqr_X",
    "fBodyGyro_iqr_Y",
    "fBodyGyro_iqr_Z",
    "fBodyGyro_entropy_X",
    "fBodyGyro_entropy_Y",
    "fBodyGyro_entropy_Z",
    "fBodyGyro_maxInds_X",
    "fBodyGyro_maxInds_Y",
    "fBodyGyro_maxInds_Z",
    "fBodyGyro_meanFreq_X",
    "fBodyGyro_meanFreq_Y",
    "fBodyGyro_meanFreq_Z",
    "fBodyGyro_skewness_X",
    "fBodyGyro_kurtosis_X",
    "fBodyGyro_skewness_Y",
    "fBodyGyro_kurtosis_Y",
    "fBodyGyro_skewness_Z",
    "fBodyGyro_kurtosis_Z",
    "fBodyGyro_bandsEnergy_18",
    "fBodyGyro_bandsEnergy_916",
    "fBodyGyro_bandsEnergy_1724",
    "fBodyGyro_bandsEnergy_2532",
    "fBodyGyro_bandsEnergy_3340",
    "fBodyGyro_bandsEnergy_4148",
    "fBodyGyro_bandsEnergy_4956",
    "fBodyGyro_bandsEnergy_5764",
    "fBodyGyro_bandsEnergy_116",
    "fBodyGyro_bandsEnergy_1732",
    "fBodyGyro_bandsEnergy_3348",
    "fBodyGyro_bandsEnergy_4964",
    "fBodyGyro_bandsEnergy_124",
    "fBodyGyro_bandsEnergy_2548",
    "fBodyGyro_bandsEnergy_18",
    "fBodyGyro_bandsEnergy_916",
    "fBodyGyro_bandsEnergy_1724",
    "fBodyGyro_bandsEnergy_2532",
    "fBodyGyro_bandsEnergy_3340",
    "fBodyGyro_bandsEnergy_4148",
    "fBodyGyro_bandsEnergy_4956",
    "fBodyGyro_bandsEnergy_5764",
    "fBodyGyro_bandsEnergy_116",
    "fBodyGyro_bandsEnergy_1732",
    "fBodyGyro_bandsEnergy_3348",
    "fBodyGyro_bandsEnergy_4964",
    "fBodyGyro_bandsEnergy_124",
    "fBodyGyro_bandsEnergy_2548",
    "fBodyGyro_bandsEnergy_18",
    "fBodyGyro_bandsEnergy_916",
    "fBodyGyro_bandsEnergy_1724",
    "fBodyGyro_bandsEnergy_2532",
    "fBodyGyro_bandsEnergy_3340",
    "fBodyGyro_bandsEnergy_4148",
    "fBodyGyro_bandsEnergy_4956",
    "fBodyGyro_bandsEnergy_5764",
    "fBodyGyro_bandsEnergy_116",
    "fBodyGyro_bandsEnergy_1732",
    "fBodyGyro_bandsEnergy_3348",
    "fBodyGyro_bandsEnergy_4964",
    "fBodyGyro_bandsEnergy_124",
    "fBodyGyro_bandsEnergy_2548",
    "fBodyAccMag_mean",
    "fBodyAccMag_std",
    "fBodyAccMag_mad",
    "fBodyAccMag_max",
    "fBodyAccMag_min",
    "fBodyAccMag_sma",
    "fBodyAccMag_energy",
    "fBodyAccMag_iqr",
    "fBodyAccMag_entropy",
    "fBodyAccMag_maxInds",
    "fBodyAccMag_meanFreq",
    "fBodyAccMag_skewness",
    "fBodyAccMag_kurtosis",
    "fBodyBodyAccJerkMag_mean",
    "fBodyBodyAccJerkMag_std",
    "fBodyBodyAccJerkMag_mad",
    "fBodyBodyAccJerkMag_max",
    "fBodyBodyAccJerkMag_min",
    "fBodyBodyAccJerkMag_sma",
    "fBodyBodyAccJerkMag_energy",
    "fBodyBodyAccJerkMag_iqr",
    "fBodyBodyAccJerkMag_entropy",
    "fBodyBodyAccJerkMag_maxInds",
    "fBodyBodyAccJerkMag_meanFreq",
    "fBodyBodyAccJerkMag_skewness",
    "fBodyBodyAccJerkMag_kurtosis",
    "fBodyBodyGyroMag_mean",
    "fBodyBodyGyroMag_std",
    "fBodyBodyGyroMag_mad",
    "fBodyBodyGyroMag_max",
    "fBodyBodyGyroMag_min",
    "fBodyBodyGyroMag_sma",
    "fBodyBodyGyroMag_energy",
    "fBodyBodyGyroMag_iqr",
    "fBodyBodyGyroMag_entropy",
    "fBodyBodyGyroMag_maxInds",
    "fBodyBodyGyroMag_meanFreq",
    "fBodyBodyGyroMag_skewness",
    "fBodyBodyGyroMag_kurtosis",
    "fBodyBodyGyroJerkMag_mean",
    "fBodyBodyGyroJerkMag_std",
    "fBodyBodyGyroJerkMag_mad",
    "fBodyBodyGyroJerkMag_max",
    "fBodyBodyGyroJerkMag_min",
    "fBodyBodyGyroJerkMag_sma",
    "fBodyBodyGyroJerkMag_energy",
    "fBodyBodyGyroJerkMag_iqr",
    "fBodyBodyGyroJerkMag_entropy",
    "fBodyBodyGyroJerkMag_maxInds",
    "fBodyBodyGyroJerkMag_meanFreq",
    "fBodyBodyGyroJerkMag_skewness",
    "fBodyBodyGyroJerkMag_kurtosis",
    "angletBodyAccMeangravity",
    "angletBodyAccJerkMeangravityMean",
    "angletBodyGyroMeangravityMean",
    "angletBodyGyroJerkMeangravityMean",
    "angleXgravityMean",
    "angleYgravityMean",
    "angleZgravityMean")


#  Measures that are mean or standard deviation
stat_measure <-
  c("tBodyAcc_mean_X",
  "tBodyAcc_mean_Y",
  "tBodyAcc_mean_Z",
  "tBodyAcc_std_X",
  "tBodyAcc_std_Y",
  "tBodyAcc_std_Z",
  "tGravityAcc_mean_X",
  "tGravityAcc_mean_Y",
  "tGravityAcc_mean_Z",
  "tGravityAcc_std_X",
  "tGravityAcc_std_Y",
  "tGravityAcc_std_Z",
  "tBodyAccJerk_mean_X",
  "tBodyAccJerk_mean_Y",
  "tBodyAccJerk_mean_Z",
  "tBodyAccJerk_std_X",
  "tBodyAccJerk_std_Y",
  "tBodyAccJerk_std_Z",
  "tBodyGyro_mean_X",
  "tBodyGyro_mean_Y",
  "tBodyGyro_mean_Z",
  "tBodyGyro_std_X",
  "tBodyGyro_std_Y",
  "tBodyGyro_std_Z",
  "tBodyGyroJerk_mean_X",
  "tBodyGyroJerk_mean_Y",
  "tBodyGyroJerk_mean_Z",
  "tBodyGyroJerk_std_X",
  "tBodyGyroJerk_std_Y",
  "tBodyGyroJerk_std_Z",
  "tBodyAccMag_mean",
  "tBodyAccMag_std",
  "tGravityAccMag_mean",
  "tGravityAccMag_std",
  "tBodyAccJerkMag_mean",
  "tBodyAccJerkMag_std",
  "tBodyGyroMag_mean",
  "tBodyGyroMag_std",
  "tBodyGyroJerkMag_mean",
  "tBodyGyroJerkMag_std",
  "fBodyAcc_mean_X",
  "fBodyAcc_mean_Y",
  "fBodyAcc_mean_Z",
  "fBodyAcc_std_X",
  "fBodyAcc_std_Y",
  "fBodyAcc_std_Z",
  "fBodyAccJerk_mean_X",
  "fBodyAccJerk_mean_Y",
  "fBodyAccJerk_mean_Z",
  "fBodyAccJerk_std_X",
  "fBodyAccJerk_std_Y",
  "fBodyAccJerk_std_Z",
  "fBodyGyro_mean_X",
  "fBodyGyro_mean_Y",
  "fBodyGyro_mean_Z",
  "fBodyGyro_std_X",
  "fBodyGyro_std_Y",
  "fBodyGyro_std_Z",
  "fBodyAccMag_mean",
  "fBodyAccMag_std",
  "fBodyBodyAccJerkMag_mean",
  "fBodyBodyAccJerkMag_std",
  "fBodyBodyGyroMag_mean",
  "fBodyBodyGyroMag_std",
  "fBodyBodyGyroJerkMag_mean",
  "fBodyBodyGyroJerkMag_std")

#  all assigned measures
assign_measure <- c("Activity", "Subject", stat_measure)

#  Descriptive text for activities
activity_desc <- 
  read.table("UCI HAR Dataset/activity_labels.txt",
             col.names=c("ActivityLabel", "Activity"),
             colClasses=c("numeric","character"))

#  Test group
#  Read motion measure vector
test_vector_data <-
  read.table("UCI HAR Dataset/test/X_test.txt",
             col.names=feature_names,
             colClasses="numeric")

#  Read subject IDs
test_subject <-
  read.table("UCI HAR Dataset/test/subject_test.txt",
             col.names="Subject",
             colClasses="numeric")

#  Read activity labels (code numbers)
test_activity_label <-
  read.table("UCI HAR Dataset/test/y_test.txt",
             col.names="ActivityLabel",
             colClasses="numeric")

#  Combine all variables
test_group <- cbind(test_activity_label,
                    test_subject,
                    test_vector_data)

#  Training group
#  Read motion measure vector
train_vector_data <-
  read.table("UCI HAR Dataset/train/X_train.txt",
             col.names=feature_names,
             colClasses="numeric")

#  Read subject IDs
train_subject <-
  read.table("UCI HAR Dataset/train/subject_train.txt",
             col.names="Subject",
             colClasses="numeric")

#  Read activity labels (code numbers)
train_activity_label <-
  read.table("UCI HAR Dataset/train/y_train.txt",
             col.names="ActivityLabel",
             colClasses="numeric")

#  Combine all variables
train_group <- cbind(test_activity_label,
                    test_subject,
                    test_vector_data)

#  Combine all observations
both_groups <- rbind(train_group, test_group)

#  Create activity text variable
both_groups$Activity <- 
  factor(both_groups$ActivityLabel, 
         activity_desc$ActivityLabel, 
         activity_desc$Activity)


#  Use only selected columns
motionstat <- both_groups[, assign_measure]

#  Compute mean by activity and subject
#  Technique based on:
#  http://gastonsanchez.com/blog/how-to/2013/02/19/Column-wise-operations-with-colwise.html
motionstat_mean <- ddply(motionstat, c("Activity", "Subject"),
                         colwise(mean))
#  Create text file from summary data

write.table(motionstat_mean, "final-project-summary.txt",
            row.names=FALSE)
